branches:
  only:
    - main

sudo: false
language: php # that way we get composer
php:
  - 7.4
install:
  - git config --global init.templatedir "$(pwd)/template"
  - git config --global user.email "travis@mailinator.com"
  - git config --global user.name "Travis Bot"
  - "mkdir -p ~/src/shunit2"
  - "git clone git://github.com/kward/shunit2.git ~/src/shunit2"
  - "svn checkout https://svn.code.sf.net/p/ctags/code/trunk ~/src/ctags"
  - "cd ~/src/ctags"
  - wget http://sourceforge.net/p/ctags/patches/_discuss/thread/3a930d9f/1405/attachment/0000-PHP-parser-rewrite.patch
  - patch -p1 < 0000-PHP-parser-rewrite.patch
  - autoconf
  - autoheader
  - ./configure
  - make
  - chmod +x ctags
  - cd -
script:
  - "export PATH=~/src/shunit2:~/src/ctags:$PATH && tests/all.sh"
